apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-grafana
    app.kubernetes.io/managed-by: Helm
  name: my-grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: my-grafana
  type: NodePort
status:
  loadBalancer: {}
