apiVersion: v1
kind: ReplicationController
metadata:
  name: "my-rc-web"
  
spec:
  replicas: 5
  selector: 
    app: "web"
  template:
    metadata: 
      name: "my-pod"
      labels:
        app: "web"
    spec:
      containers: 
        - name: "my-c"
          image: vimal13/apache-webserver-php
      
      