apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myd"
  labels:
    type: "Production-deployment"
  
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: "web"
  template:
    metadata: 
      name: "my-pod"
      labels:
        app: "web"
    spec:
      volumes: 
        - name: "my-volume"
          persistentVolumeClaim: 
            claimName: "my-pvc"
      containers: 
        - name: "my-c"
          image: vimal13/apache-webserver-php
          volumeMounts:
            - mountPath: /var/www/html
              name: "my-volume"
      
      